Repository ckotzbauer/helm-charts, pull requests merged in 2020-09, with the labels that each got.

#25 Add imagePullSecrets
  charts/cadvisor/Chart.yaml
  charts/cadvisor/README.md
  charts/cadvisor/templates/daemonset.yaml
  charts/cadvisor/values.yaml
Labels: kind/feature, size/S

#26 chore: Update appVersion and psp as privileged
  charts/cadvisor/Chart.yaml
  charts/cadvisor/README.md
  charts/cadvisor/templates/psp.yaml
  charts/cadvisor/values.yaml
Labels: approved, kind/feature, size/M

#28 update access-manager to 0.4.0
  charts/access-manager/Chart.yaml
  charts/access-manager/README.md
  charts/access-manager/crds/rbacdefinitions.yaml
  charts/access-manager/values.yaml
Labels: approved, kind/feature, size/S
