Repository ckotzbauer/helm-charts, pull requests merged in 2020-11, with the labels that each got.

#33 Update access-manager to 0.4.1
  charts/access-manager/Chart.yaml
  charts/access-manager/README.md
  charts/access-manager/templates/crd.yaml
  charts/access-manager/values.yaml
Labels: size/S

#34 Update blackbox-exporter to 0.18.0
  charts/prometheus-blackbox-exporter/Chart.yaml
  charts/prometheus-blackbox-exporter/README.md
  charts/prometheus-blackbox-exporter/values.yaml
Labels: size/XS

#39 update cadvisor to 0.38.4
  charts/cadvisor/Chart.yaml
  charts/cadvisor/README.md
  charts/cadvisor/values.yaml
Labels: kind/feature, size/M

#38 add accessModes
  charts/nfs-client-provisioner/Chart.yaml
  charts/nfs-client-provisioner/README.md
  charts/nfs-client-provisioner/templates/persistentvolume.yaml
  charts/nfs-client-provisioner/templates/persistentvolumeclaim.yaml
  charts/nfs-client-provisioner/values.yaml
Labels: kind/feature, size/M
